# Project 1: First Data Exploration

## Objective
Explore a real stellar dataset using pandas and matplotlib to answer basic questions about stars.

## Introduction
The data set, Stellar Classification Dataset - SDSS17, is a machine learning dataset that contains  100,000 celestial observations from the Sloan Digital Sky Survey Data Release 17. In astronomy, stellar classification is the classification of stars based on their spectral characteristics. The classification scheme of galaxies, quasars, and stars is one of the most fundamental in astronomy as it has led to the understanding that they make up our own galaxy and helped us survey many more galaxies.

First, we import libraries and download the data set. Run the cell below.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sdss17 = pd.read_csv("../data/star_classification.csv")

## Looking at the Data
Now we can look at the data to answer questions, but before we introduce questions, we need to go over fundamental operations that will help us be effective data scientists.

The data consists of 100,000 observations of space taken by the Sloan Digital Sky Survey (SDSS). Each observation is described by 17 feature columns and 1 class column which identifies it to be either a star, galaxy or quasar. Before we open the data, we can first preview it in different ways!.

In [28]:
# This shows the first five rows
sdss17.head()

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
0,1.237661e+18,135.689107,32.494632,23.87882,22.27530,20.39501,19.16573,18.79371,3606,301,2,79,6.543777e+18,GALAXY,0.634794,5812,56354,171
1,1.237665e+18,144.826101,31.274185,24.77759,22.83188,22.58444,21.16812,21.61427,4518,301,5,119,1.176014e+19,GALAXY,0.779136,10445,58158,427
2,1.237661e+18,142.188790,35.582444,25.26307,22.66389,20.60976,19.34857,18.94827,3606,301,2,120,5.152200e+18,GALAXY,0.644195,4576,55592,299
3,1.237663e+18,338.741038,-0.402828,22.13682,23.77656,21.61162,20.50454,19.25010,4192,301,3,214,1.030107e+19,GALAXY,0.932346,9149,58039,775
4,1.237680e+18,345.282593,21.183866,19.43718,17.58028,16.49747,15.97711,15.54461,8102,301,3,137,6.891865e+18,GALAXY,0.116123,6121,56187,842

In [29]:
# This shows the last five rows
sdss17.tail()

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
99995,1.237679e+18,39.620709,-2.594074,22.16759,22.97586,21.90404,21.30548,20.73569,7778,301,2,581,1.055431e+19,GALAXY,0.000000,9374,57749,438
99996,1.237679e+18,29.493819,19.798874,22.69118,22.38628,20.45003,19.75759,19.41526,7917,301,1,289,8.586351e+18,GALAXY,0.404895,7626,56934,866
99997,1.237668e+18,224.587407,15.700707,21.16916,19.26997,18.20428,17.69034,17.35221,5314,301,4,308,3.112008e+18,GALAXY,0.143366,2764,54535,74
99998,1.237661e+18,212.268621,46.660365,25.35039,21.63757,19.91386,19.07254,18.62482,3650,301,4,131,7.601080e+18,GALAXY,0.455040,6751,56368,470
99999,1.237661e+18,196.896053,49.464643,22.62171,21.79745,20.60115,20.00959,19.28075,3650,301,4,60,8.343152e+18,GALAXY,0.542944,7410,57104,851

In [116]:
# These shows the statistics
print(sdss17.describe())
print()
print("Mean of the 'alpha' column:", sdss17.alpha.mean())

             obj_ID          alpha          delta              u  \
count  1.000000e+05  100000.000000  100000.000000  100000.000000
mean   1.237665e+18     177.629117      24.135305      21.980468
std    8.438560e+12      96.502241      19.644665      31.769291
min    1.237646e+18       0.005528     -18.785328   -9999.000000
25%    1.237659e+18     127.518222       5.146771      20.352353
50%    1.237663e+18     180.900700      23.645922      22.179135
75%    1.237668e+18     233.895005      39.901550      23.687440
max    1.237681e+18     359.999810      83.000519      32.781390

                   g              r              i              z  \
count  100000.000000  100000.000000  100000.000000  100000.000000
mean       20.531387      19.645762      19.084854      18.668810
std        31.750292       1.854760       1.757895      31.728152
min     -9999.000000       9.822070       9.469903   -9999.000000
25%        18.965230      18.135828      17.732285      17.460677
50%        21.099835      20.125290      19.405145      19.004595
75%        22.123767      21.044785      20.396495      19.921120
max        31.602240      29.571860      32.141470      29.383740

              run_ID  rerun_ID        cam_col       field_ID   spec_obj_ID  \
count  100000.000000  100000.0  100000.000000  100000.000000  1.000000e+05
mean     4481.366060     301.0       3.511610     186.130520  5.783882e+18
std      1964.764593       0.0       1.586912     149.011073  3.324016e+18
min       109.000000     301.0       1.000000      11.000000  2.995191e+17
25%      3187.000000     301.0       2.000000      82.000000  2.844138e+18
50%      4188.000000     301.0       4.000000     146.000000  5.614883e+18
75%      5326.000000     301.0       5.000000     241.000000  8.332144e+18
max      8162.000000     301.0       6.000000     989.000000  1.412694e+19

            redshift          plate            MJD       fiber_ID
count  100000.000000  100000.000000  100000.000000  100000.000000
mean        0.576661    5137.009660   55588.647500     449.312740
std         0.730707    2952.303351    1808.484233     272.498404
min        -0.009971     266.000000   51608.000000       1.000000
25%         0.054517    2526.000000   54234.000000     221.000000
50%         0.424173    4987.000000   55868.500000     433.000000
75%         0.704154    7400.250000   56777.000000     645.000000
max         7.011245   12547.000000   58932.000000    1000.000000

Mean of the 'alpha' column: 177.6291166216363

In [111]:
# This tells you how many missing values each column has
sdss17.isnull().sum()

obj_ID         0
alpha          0
delta          0
u              0
g              0
r              0
i              0
z              0
run_ID         0
rerun_ID       0
cam_col        0
field_ID       0
spec_obj_ID    0
class          0
redshift       0
plate          0
MJD            0
fiber_ID       0
dtype: int64

In [45]:
# This displays a list of the columns.
sdss17.columns

Index(['obj_ID', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'run_ID',
       'rerun_ID', 'cam_col', 'field_ID', 'spec_obj_ID', 'class', 'redshift',
       'plate', 'MJD', 'fiber_ID'],
      dtype='str')

Now that we can preview the table, let's establish what all these columns represent.
1. obj_ID = Object Identifier, the unique value that identifies the object in the image catalog used by the CAS
2. alpha = Right Ascension angle (at J2000 epoch)
3. delta = Declination angle (at J2000 epoch)
4. u = Ultraviolet filter in the photometric system
5. g = Green filter in the photometric system
6. r = Red filter in the photometric system
7. i = Near Infrared filter in the photometric system
8. z = Infrared filter in the photometric system
9. run_ID = Run Number used to identify the specific scan
10. rereun_ID = Rerun Number to specify how the image was processed
11. cam_col = Camera column to identify the scanline within the run
12. field_ID = Field number to identify each field
13. spec_obj_ID = Unique ID used for optical spectroscopic objects (this means that 2 different observations with the same spec_obj_ID must share the output class)
14. class = object class (galaxy, star or quasar object)
15. redshift = redshift value based on the increase in wavelength
16. plate = plate ID, identifies each plate in SDSS
17. MJD = Modified Julian Date, used to indicate when a given piece of SDSS data was taken
18. fiber_ID = fiber ID that identifies the fiber that pointed the light at the focal plane in each observation

To determine the shape (number of rows, number of columns):

In [43]:
print(sdss17.shape)
# You can also access them separately
print(sdss17.shape[0])
print(sdss17.shape[1])

(100000, 18)
100000
18

To view data types:

In [47]:
sdss17.dtypes

obj_ID         float64
alpha          float64
delta          float64
u              float64
g              float64
r              float64
i              float64
z              float64
run_ID           int64
rerun_ID         int64
cam_col          int64
field_ID         int64
spec_obj_ID    float64
class              str
redshift       float64
plate            int64
MJD              int64
fiber_ID         int64
dtype: object

To see uniqueness:

In [159]:
print(sdss17.nunique()) # This returns the number of unique values
print()
print("Number of unique values in 'class' column:", sdss17['class'].nunique())
print(sdss17["class"].unique())
# To see how many times each value appears in a column
print(sdss17['class'].value_counts())

obj_ID          78053
alpha           99999
delta           99999
u               93748
g               92651
r               91901
i               92019
z               92007
run_ID            430
rerun_ID            1
cam_col             6
field_ID          856
spec_obj_ID    100000
class               3
redshift        99295
plate            6284
MJD              2180
fiber_ID         1000
dtype: int64

Number of unique values in 'class' column: 3
<StringArray>
['GALAXY', 'QSO', 'STAR']
Length: 3, dtype: str
class
GALAXY    59445
STAR      21594
QSO       18961
Name: count, dtype: int64

This next method summarizes all the above, plus memory usage

In [48]:
sdss17.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   obj_ID       100000 non-null  float64
 1   alpha        100000 non-null  float64
 2   delta        100000 non-null  float64
 3   u            100000 non-null  float64
 4   g            100000 non-null  float64
 5   r            100000 non-null  float64
 6   i            100000 non-null  float64
 7   z            100000 non-null  float64
 8   run_ID       100000 non-null  int64
 9   rerun_ID     100000 non-null  int64
 10  cam_col      100000 non-null  int64
 11  field_ID     100000 non-null  int64
 12  spec_obj_ID  100000 non-null  float64
 13  class        100000 non-null  str
 14  redshift     100000 non-null  float64
 15  plate        100000 non-null  int64
 16  MJD          100000 non-null  int64
 17  fiber_ID     100000 non-null  int64
dtypes: float64(10), int64(7), str(1)
memory usage: 13.7 MB

### Reflection
Just from these methods, I have learned a lot of useful information about the dataset before I jumped into selecting, sorting, or other tools. The table has 1000 rows and 18 columns. This is a complete data set, meaning there are no missing values. There is one categorical column called 'class' which classifies into 3 unique values. There are more galaxies than there are quasars and stars, and quasars is the smallest category.
All other columns are numeric. The most useful columns for analysis will likely be:
- class: to compare different object types
- redshift: to study distance-related patterns
- u, g, r, i, z: to analyze brightness and color differences
- MJD: to study observation timing

Some columns such as obj_ID and fiber_ID are identifiers and may not provide scientific measurements but are useful for tracking observations.

## Indexing
The indexing operator and attribute selection are great because they work just like they do in the rest of the Python language. However, pandas has its own accessor operators, loc and iloc.

Looking at the table alone looks like a huge mess of information and can be overwhelming. An important skill in Python is being able to select the data points that are relevant to you.

In Python, we can access the property of an object by accessing it as an attribute.

In [17]:
sdss17.obj_ID

0        1.237661e+18
1        1.237665e+18
2        1.237661e+18
3        1.237663e+18
4        1.237680e+18
             ...
99995    1.237679e+18
99996    1.237679e+18
99997    1.237668e+18
99998    1.237661e+18
99999    1.237661e+18
Name: obj_ID, Length: 100000, dtype: float64

The indexing operator and attribute selection are great because they work just like they do in the rest of the Python language. However, pandas has its own accessor operators, loc and iloc.

In [29]:
str(sdss17['obj_ID'][0]) # NOTE: Notice that the data is in float form. We must convert to string for readable output.

'1.2376609613277432e+18'

Pandas indexing works in one of two ways. The first is an index-based selection where we select data based on its numerical position in the data. The way to do this is through iloc.

To select the first row of data in a DataFrame, we may:

In [31]:
sdss17.iloc[0]

obj_ID         1237660961327743232.0
alpha                     135.689107
delta                      32.494632
u                           23.87882
g                            22.2753
r                           20.39501
i                           19.16573
z                           18.79371
run_ID                          3606
rerun_ID                         301
cam_col                            2
field_ID                          79
spec_obj_ID    6543777369295181824.0
class                         GALAXY
redshift                    0.634794
plate                           5812
MJD                            56354
fiber_ID                         171
Name: 0, dtype: object

Both loc and iloc are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second. This means that it's easier to retrieve rows, but harder to retrieve columns. 

To get a column with iloc, we can do:

In [32]:
sdss17.iloc[:,0]

0        1.237661e+18
1        1.237665e+18
2        1.237661e+18
3        1.237663e+18
4        1.237680e+18
             ...
99995    1.237679e+18
99996    1.237679e+18
99997    1.237668e+18
99998    1.237661e+18
99999    1.237661e+18
Name: obj_ID, Length: 100000, dtype: float64

The slice operator, or the : operator, when combined with other selectors, can be used to indicate a range of values. Because iloc means integer-location indexing, it selects rows and columns by their position (starting at 0). In this case, it's asked for all the rows but only for the first column. 

The general format of iloc is df.iloc[rows, columns]. If you provide only one argument, like we did the first example, pandas assumes you're talking about the rows.

The second way for attribute selection is the one followed by the loc operator, or label-based selection. In this, it's the data index value, not its position, which matters.

In [35]:
str(sdss17.loc[0, 'obj_ID'])

'1.2376609613277432e+18'

When to Use Which?
- Use .loc when you have stable, meaningful index labels (like dates or IDs) and you want your code to remain human-readable.
- Use .iloc when you want to look up data purely by structure (e.g., getting the "first 5 rows" or "the last column") regardless of what the labels are

#### Conditional Selection

To do interesting things with the data, however, we often need to ask questions based on conditions.

For example, say we are interested in the objects that are classified as a quasar.

First, we can count how many values are in each category.

In [70]:
sdss17["class"].value_counts()

class
GALAXY    59445
STAR      21594
QSO       18961
Name: count, dtype: int64

In pandas, the most common way to filter rows is Boolean indexing.

In [69]:
sdss17[sdss17["class"] == "QSO"]

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
5,1.237680e+18,340.995121,20.589476,23.48827,23.33776,21.32195,20.25615,19.54544,8102,301,3,110,5.658977e+18,QSO,1.424659,5026,55855,741
6,1.237679e+18,23.234926,11.418188,21.46973,21.17624,20.92829,20.60826,20.42573,7773,301,2,462,1.246262e+19,QSO,0.586455,11069,58456,113
17,1.237679e+18,1.494389,3.291746,20.38562,20.40514,20.29996,20.05918,19.89044,7712,301,5,339,9.843824e+18,QSO,2.031528,8743,57663,295
23,1.237658e+18,145.883006,47.300484,21.73992,21.53095,21.26763,21.36257,21.15861,2821,301,2,33,8.228240e+18,QSO,2.075680,7308,56709,596
33,1.237679e+18,20.052556,11.497881,21.89214,21.35124,21.18755,20.84300,20.76580,7773,301,2,441,1.246830e+19,QSO,1.528308,11074,58488,306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99961,1.237655e+18,134.347759,47.771911,24.17897,22.89025,21.26451,20.94941,19.87500,2243,301,4,128,8.458979e+18,QSO,0.219966,7513,56780,339
99966,1.237662e+18,222.761686,32.203212,20.23421,19.76480,19.46940,19.36135,19.21768,3900,301,1,583,4.356138e+18,QSO,0.398574,3869,55273,112
99968,1.237656e+18,259.504325,31.462416,24.86685,23.22772,21.82982,21.80359,21.56733,2335,301,5,107,1.312146e+19,QSO,1.239638,11654,58543,812
99977,1.237661e+18,217.958430,52.316738,24.15617,22.05986,21.80826,21.95129,21.24179,3705,301,2,124,7.916218e+18,QSO,1.067543,7031,56449,58
99980,1.237662e+18,225.566376,32.118746,20.53765,19.93229,19.77495,19.72304,19.40202,3900,301,3,598,4.357250e+18,QSO,2.488738,3870,55273,62

In [85]:
sdss17.loc[
    sdss17["class"] == "QSO"
]

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
5,1.237680e+18,340.995121,20.589476,23.48827,23.33776,21.32195,20.25615,19.54544,8102,301,3,110,5.658977e+18,QSO,1.424659,5026,55855,741
6,1.237679e+18,23.234926,11.418188,21.46973,21.17624,20.92829,20.60826,20.42573,7773,301,2,462,1.246262e+19,QSO,0.586455,11069,58456,113
17,1.237679e+18,1.494389,3.291746,20.38562,20.40514,20.29996,20.05918,19.89044,7712,301,5,339,9.843824e+18,QSO,2.031528,8743,57663,295
23,1.237658e+18,145.883006,47.300484,21.73992,21.53095,21.26763,21.36257,21.15861,2821,301,2,33,8.228240e+18,QSO,2.075680,7308,56709,596
33,1.237679e+18,20.052556,11.497881,21.89214,21.35124,21.18755,20.84300,20.76580,7773,301,2,441,1.246830e+19,QSO,1.528308,11074,58488,306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99961,1.237655e+18,134.347759,47.771911,24.17897,22.89025,21.26451,20.94941,19.87500,2243,301,4,128,8.458979e+18,QSO,0.219966,7513,56780,339
99966,1.237662e+18,222.761686,32.203212,20.23421,19.76480,19.46940,19.36135,19.21768,3900,301,1,583,4.356138e+18,QSO,0.398574,3869,55273,112
99968,1.237656e+18,259.504325,31.462416,24.86685,23.22772,21.82982,21.80359,21.56733,2335,301,5,107,1.312146e+19,QSO,1.239638,11654,58543,812
99977,1.237661e+18,217.958430,52.316738,24.15617,22.05986,21.80826,21.95129,21.24179,3705,301,2,124,7.916218e+18,QSO,1.067543,7031,56449,58
99980,1.237662e+18,225.566376,32.118746,20.53765,19.93229,19.77495,19.72304,19.40202,3900,301,3,598,4.357250e+18,QSO,2.488738,3870,55273,62

In [86]:
sdss17.loc[
    sdss17["class"] == "GALAXY",
    ['obj_ID', 'field_ID', 'class', 'redshift']
]

             obj_ID  field_ID   class  redshift
0      1.237661e+18        79  GALAXY  0.634794
1      1.237665e+18       119  GALAXY  0.779136
2      1.237661e+18       120  GALAXY  0.644195
3      1.237663e+18       214  GALAXY  0.932346
4      1.237680e+18       137  GALAXY  0.116123
...             ...       ...     ...       ...
99995  1.237679e+18       581  GALAXY  0.000000
99996  1.237679e+18       289  GALAXY  0.404895
99997  1.237668e+18       308  GALAXY  0.143366
99998  1.237661e+18       131  GALAXY  0.455040
99999  1.237661e+18        60  GALAXY  0.542944

[59445 rows x 4 columns]

The term redshift measures how much the light from a distant celestial object is stretched to longer (redder) wavelengths as it travels through our expanding universe. The higher the redshift, the farther away the object is and the further back in time we are looking. A high red shift means that the object is further away and you are looking further back in time. So what if I wanted all the quasars with a red shift that is higher than 1?

In [76]:
sdss17[(sdss17["class"] == "QSO")
    & (sdss17["redshift"] > 1)]

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
5,1.237680e+18,340.995121,20.589476,23.48827,23.33776,21.32195,20.25615,19.54544,8102,301,3,110,5.658977e+18,QSO,1.424659,5026,55855,741
17,1.237679e+18,1.494389,3.291746,20.38562,20.40514,20.29996,20.05918,19.89044,7712,301,5,339,9.843824e+18,QSO,2.031528,8743,57663,295
23,1.237658e+18,145.883006,47.300484,21.73992,21.53095,21.26763,21.36257,21.15861,2821,301,2,33,8.228240e+18,QSO,2.075680,7308,56709,596
33,1.237679e+18,20.052556,11.497881,21.89214,21.35124,21.18755,20.84300,20.76580,7773,301,2,441,1.246830e+19,QSO,1.528308,11074,58488,306
47,1.237668e+18,228.447728,12.745032,22.36261,21.71060,21.59630,21.60179,21.12727,5322,301,3,125,6.179027e+18,QSO,2.689002,5488,56013,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99938,1.237680e+18,355.179454,27.714932,21.50280,21.59604,21.42026,21.01734,20.47349,8103,301,5,67,8.667300e+18,QSO,1.794403,7698,58013,444
99949,1.237679e+18,34.602921,31.514091,22.45167,21.19384,20.60153,20.56568,20.14365,7781,301,4,148,8.712484e+18,QSO,2.418509,7738,58100,985
99968,1.237656e+18,259.504325,31.462416,24.86685,23.22772,21.82982,21.80359,21.56733,2335,301,5,107,1.312146e+19,QSO,1.239638,11654,58543,812
99977,1.237661e+18,217.958430,52.316738,24.15617,22.05986,21.80826,21.95129,21.24179,3705,301,2,124,7.916218e+18,QSO,1.067543,7031,56449,58
99980,1.237662e+18,225.566376,32.118746,20.53765,19.93229,19.77495,19.72304,19.40202,3900,301,3,598,4.357250e+18,QSO,2.488738,3870,55273,62

Or what if we wanted all galaxies that are between a certain range in red shift?

In [84]:
sdss17[(sdss17["class"] == "GALAXY")
    & (sdss17["redshift"].between(1,1.5))]

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID
46,1.237679e+18,40.795743,3.564368,22.79262,22.29579,22.23841,21.55672,21.01273,7718,301,2,261,1.060281e+19,GALAXY,1.065883,9417,58055,748
316,1.237659e+18,214.922437,56.621721,25.15787,23.76707,23.05294,21.23330,19.83673,3225,301,4,57,9.455445e+18,GALAXY,1.030206,8398,57870,499
441,1.237665e+18,144.855506,31.285645,25.10174,23.06618,22.55700,21.52077,20.81181,4518,301,5,119,1.176013e+19,GALAXY,1.017365,10445,58158,387
774,1.237663e+18,340.800729,-0.291503,22.35328,22.61955,22.05798,21.83292,21.26052,4192,301,3,228,1.037769e+19,GALAXY,1.002869,9217,57934,984
855,1.237678e+18,44.420238,3.120954,23.58547,23.11111,22.95522,22.39829,22.27241,7675,301,6,165,1.059946e+19,GALAXY,1.371361,9414,58083,859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99561,1.237664e+18,25.576386,-0.341028,22.71957,22.05721,21.57762,21.38845,20.67397,4263,301,3,286,1.058236e+19,GALAXY,1.068152,9399,58125,105
99767,1.237679e+18,13.060716,-3.203539,23.63581,22.41118,21.69165,21.37523,22.94800,7907,301,2,159,1.051387e+19,GALAXY,1.019857,9338,58044,799
99768,1.237679e+18,15.057399,-3.278247,22.59929,22.39242,21.96018,21.58924,22.23776,7907,301,2,172,1.051502e+19,GALAXY,1.053769,9339,57692,876
99787,1.237664e+18,4.183052,-0.377762,21.91764,21.95530,21.54452,21.42748,21.85878,4263,301,3,143,1.059026e+19,GALAXY,1.059405,9406,58067,173
99882,1.237662e+18,244.105595,34.121818,22.47669,22.31934,22.01662,22.12782,22.14425,3918,301,4,308,1.228607e+19,GALAXY,1.038119,10912,58253,902

Now suppose I want a table that have objects that are either quasars or galaxies, and have a high redshift, and don't all this unnecessary other information.

In [106]:
sdss17[
    ((sdss17['class'] == "QSO") | (sdss17['class'] == "GALAXY")) &
    (sdss17['redshift'] > 1)
    ].loc[:, ['obj_ID', 'class', 'redshift']]

             obj_ID   class  redshift
5      1.237680e+18     QSO  1.424659
17     1.237679e+18     QSO  2.031528
23     1.237658e+18     QSO  2.075680
33     1.237679e+18     QSO  1.528308
46     1.237679e+18  GALAXY  1.065883
...             ...     ...       ...
99938  1.237680e+18     QSO  1.794403
99949  1.237679e+18     QSO  2.418509
99968  1.237656e+18     QSO  1.239638
99977  1.237661e+18     QSO  1.067543
99980  1.237662e+18     QSO  2.488738

[15988 rows x 3 columns]

That's a lot of boolean expressions. We can simplify a little bit using a new method called .isin, and instead of hardcoding, we can use sequences.

In [108]:
columns = ['obj_ID', 'class', 'redshift']
classes = ["QSO", "GALAXY"]
sdss17[
    (sdss17['class'].isin(classes)) &
    (sdss17['redshift'] > 1)
].loc[:, columns]

             obj_ID   class  redshift
5      1.237680e+18     QSO  1.424659
17     1.237679e+18     QSO  2.031528
23     1.237658e+18     QSO  2.075680
33     1.237679e+18     QSO  1.528308
46     1.237679e+18  GALAXY  1.065883
...             ...     ...       ...
99938  1.237680e+18     QSO  1.794403
99949  1.237679e+18     QSO  2.418509
99968  1.237656e+18     QSO  1.239638
99977  1.237661e+18     QSO  1.067543
99980  1.237662e+18     QSO  2.488738

[15988 rows x 3 columns]

Filtering is important because real datasets are usually too large to analyze all at once. Researchers and data scientists filter data to focus on specific groups and answer targeted questions.

## Mapping
A map describes a function that takes one set of values and "maps" them to another set of values. In data science, we often  need to create new representations from existing data, or for transforming data from the format it is in now into the format that we want it to be in later on. Maps are what handle this work, making them extremely important for getting your work done!

### map()

map() takes every value in a column and replaces it with something else based on a rule. You can think of it as a translator. It's common pattern is df["column"].map(dictionary) or df["column"].map(function). Let's see it in action!

Suppose you have a table which has a categorical column, but the labels they use are hard to read. We can map each label to an easier one to read using a dictionary.

In [28]:
class_names = {
    "GALAXY": "Galaxy",
    "STAR": "Star",
    "QSO": "Quasar"
}
sdss17["class"].map(class_names)

0        Galaxy
1        Galaxy
2        Galaxy
3        Galaxy
4        Galaxy
          ...
99995    Galaxy
99996    Galaxy
99997    Galaxy
99998    Galaxy
99999    Galaxy
Name: class, Length: 100000, dtype: str

Our table, sdss17, has a column called 'MJD' or Modified Julian Date, and it's a way astronomers record when an observation happened using a single number. Astronomers use it because normal calendar dates (like "July 20, 2026") are inconvenient for calculations. A telescope might collect millions of observations, so researchers need a format that computers can easily compare and calculate. MJD is a count of days since a reference date. In this case, MJD 0 = November 17, 1858 (00:00 UTC). The larger the MJD, the more recent the observation.

In [160]:
# What is the oldest observation?
oldest_date = sdss17["MJD"].min()
oldest_observation = sdss17["MJD"].idxmax()
print(f"Object #{oldest_observation} is the oldest observation with MJD {oldest_date}")

974 is the oldest observation with MJD 51608

In [162]:
# What is most recent observation?
recent_date = sdss17["MJD"].max()
recent_observation = sdss17["MJD"].idxmin()
print(f"Object #{recent_observation} is the most recent observation with MJD {recent_date}")

Object #5390 is the most recent observation with MJD 58932

Suppose we want to categorize each object as an older or more recent observation.

In [131]:
diff = recent_date - oldest_date
midpoint = oldest_date + diff / 2

# First define a function
def classify_observation(mjd):
    if mjd < midpoint:
        return "Early Survey"
    else:
        return "Late Survey"


sdss17["MJD"].map(classify_observation)

0         Late Survey
1         Late Survey
2         Late Survey
3         Late Survey
4         Late Survey
             ...
99995     Late Survey
99996     Late Survey
99997    Early Survey
99998     Late Survey
99999     Late Survey
Name: MJD, Length: 100000, dtype: str

The function you pass to map() should expect a single value from the Series and return a transformed version of that value. map() returns a new Series where all the values have been transformed by your function.

### apply()

Another way to map is through apply(). apply() is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row.

The easiest way to think about it:
- map() → apply a function to each value in one column
- apply() → apply a function to a whole column or a whole row

The difference is when you want to use multiple columns together.

A photometric system defines the standardized filters, detectors, and mathematical scales used to measure the intensity of light. In astronomy, it classifies celestial objects based on brightness across specific ultraviolet, visible, and infrared wavelengths. In photometry systems, filters like the Red (R) filter let astronomers calculate an object's magnitude (a measure of brightness) in just red light. It tells you how much red light the object is emitting. Notice in our table we have multiple filters.

| Column | Filter | Measures |
|--------|--------|----------|
| u | Ultraviolet | Amount of UV light |
| g | Green | Amount of green visible light |
| r | Red | Amount of red visible light |
| i | Near-infrared | Amount of near-IR light |
| z | Infrared | Amount of IR light |

Now, suppose we want to classify objects based on what color they are. Astronomers often use differences between filters. Astronomers subtract the magnitude of the shorter-wavelength filter from the longer-wavelength filter. Because the Green (g) and Red (r) filters are both in the visible range and provide reliable measurements, we use the g-r color index to measure differences in the colors of astronomical objects. This allows us to compare how much light objects emit at shorter versus longer wavelengths. A smaller number indicates a hotter, bluer object, while a larger number indicates a cooler, redder one.

In [30]:
def classify_color(row):
    color_index = row["g"] - row["r"]

    if color_index < 0:
        return "Bluer Object"
    else:
        return "Redder Object"

sdss17["g_r_color"] = sdss17.apply(classify_color, axis=1)

sdss17["g_r_color"].value_counts()

g_r_color
Redder Object    95701
Bluer Object      4299
Name: count, dtype: int64

Why axis=1?
- axis=0 → apply to each column
- axis=1 → apply to each row

### Reflection
I used apply() to create a new feature based on multiple columns. The g-r color index compares the brightness of an object in the green and red filters. A smaller color index generally indicates a bluer object, while a larger value indicates a redder object. I created a classification column to group objects based on their color index. However, real astronomy is more nuanced because the cutoff depends on what you are studying. A galaxy with g-r = 0.8 might be considered blue compared to an older galaxy. Astronomers often look at the distribution of colors instead, which we will do later on to try and more accurately classify.

## Grouping & Sorting
Grouping and sorting data are fundamental data techniques that transform raw, unstructured information into organized, readable, and actionable formats. They are great for information retrieval, spotting hidden trends, and simplifying complex data.

### groupby()
The groupby() method in pandas partitions a DataFrame into distinct groups to perform calculations. It executes the Split-Apply-Combine strategy: splitting data based on specified criteria, applying a function (like calculation or filtering), and combining the results into a new dataset. groupby() splits your data into groups based on one or more columns, then lets you perform calculations on each group.

The basic syntax is df.groupby("column") and is usually followed by an aggregation.

Suppose we want to know the average redshift for each object type?

In [24]:
# Group by class, then work only with the redshift column.
sdss17.groupby("class")["redshift"].mean()

class
GALAXY    0.421596
QSO       1.719676
STAR     -0.000115
Name: redshift, dtype: float64

The first part sdss17.groupby("class") creates a GroupBy object where nothing is calculated yet. A GroupBy object is a special, intermediate container that holds your data segmented into distinct groups, but does not compute or display a new data table immediately. Pandas maps out which rows belong to which categories, but doesn't calculate anything until you explicitly tell it what operation to perform on those groups. In this case, our operation was mean()

In [25]:
# You can work with multiple columns
sdss17.groupby("class")[["u", "g", "r"]].mean()

                u          g          r
class
GALAXY  22.587379  20.906101  19.587552
QSO     21.547619  20.926193  20.624089
STAR    20.689805  19.153188  18.946969

In [166]:
# You can apply multiple aggregations too
sdss17.groupby("class")["redshift"].agg(["mean", "min", "max"])

            mean       min       max
class
GALAXY  0.421596 -0.009971  1.995524
QSO     1.719676  0.000461  7.011245
STAR   -0.000115 -0.004136  0.004153

MultiIndexes are something you'll start seeing once you use groupby() more. They look confusing at first, but they're just multiple labels used as an index instead of one.

Notice our past examples, our indices went from the generic 0, 1, 2, 3, 4... you see in the original dataframe to GALAXY, QSO, STAR. Now, suppose we group by two columns.

In [26]:
sdss17.groupby(["class", "g_r_color"])["redshift"].mean()

class   g_r_color
GALAXY  Bluer Object     0.590306
        Redder Object    0.419638
QSO     Bluer Object     1.848355
        Redder Object    1.701295
STAR    Bluer Object    -0.000106
        Redder Object   -0.000115
Name: redshift, dtype: float64

Now pandas needs two labels to identify each row. Instead of treating class and g_r_color as normal columns, pandas makes them a MultiIndex. 

Multi-indices have several methods for dealing with their tiered structure which are absent for single-level indices. They also require two levels of labels to retrieve a value. Many beginners prefer normal columns.

In [27]:
sdss17.groupby(["class", "g_r_color"])["redshift"].mean().reset_index()

    class      g_r_color  redshift
0  GALAXY   Bluer Object  0.590306
1  GALAXY  Redder Object  0.419638
2     QSO   Bluer Object  1.848355
3     QSO  Redder Object  1.701295
4    STAR   Bluer Object -0.000106
5    STAR  Redder Object -0.000115

Grouping returns data in index order, not in value order. When outputting the result of a groupby, the order of the rows is dependent on the values in the index, not in the data.

### sort_values()
sort_values() sorts the DataFrame based on the values in one or more columns.

In [175]:
sdss17.sort_values(by="redshift")

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID,g_r_color
46334,1.237668e+18,167.242339,17.894783,22.06989,21.51930,21.41494,21.30507,21.21390,5313,301,1,54,6.629341e+18,GALAXY,-0.009971,5888,56041,154,Redder Object
66040,1.237652e+18,152.041107,64.524210,26.94855,23.41462,18.08402,22.93524,21.96446,1412,301,5,79,5.495439e+17,GALAXY,-0.007352,488,51914,381,Redder Object
8650,1.237665e+18,152.043506,33.555225,22.73689,21.89153,21.90507,21.91927,21.43474,4518,301,5,162,7.273397e+18,GALAXY,-0.006863,6460,56334,302,Bluer Object
31976,1.237668e+18,241.444339,11.504581,22.63915,22.00861,21.91697,21.83613,21.57314,5317,301,4,120,5.859379e+18,GALAXY,-0.006055,5204,56036,714,Redder Object
39518,1.237680e+18,15.833059,30.322466,23.51236,23.47375,23.24541,21.54165,19.52259,8105,301,5,47,8.693348e+18,GALAXY,-0.005675,7721,57360,999,Redder Object
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6178,1.237659e+18,229.108555,51.516024,24.04846,22.78807,21.51426,20.52233,19.77332,3225,301,4,122,9.452082e+18,QSO,7.011245,8395,57834,555,Redder Object
62078,1.237680e+18,29.769097,28.623509,26.34246,22.30740,19.91426,19.80399,18.96863,8097,301,6,46,8.709981e+18,QSO,7.011245,7736,57728,68,Redder Object
51922,1.237679e+18,317.068681,7.730935,25.14270,23.50900,21.78374,20.47938,19.80522,7777,301,2,39,1.274191e+19,QSO,7.011245,11317,58398,353,Redder Object
53375,1.237668e+18,164.524385,21.966377,24.77107,21.62430,19.98343,19.17728,18.73189,5183,301,5,223,7.237420e+18,QSO,7.011245,6428,56279,493,Redder Object
71744,1.237673e+18,347.394204,23.192555,26.78221,21.71899,20.29786,19.29930,19.03935,6354,301,4,176,7.419807e+18,QSO,7.011245,6590,56273,461,Redder Object

This arranges objects from the smallest redshift to the largest. To sort from largest to smallest:

In [177]:
sdss17.sort_values(by="redshift", ascending=False)

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID,g_r_color
39650,1.237663e+18,327.236414,0.146625,25.27025,23.12677,22.19393,20.92240,19.95898,4192,301,4,137,1.029435e+19,QSO,7.011245,9143,57665,909,Redder Object
51922,1.237679e+18,317.068681,7.730935,25.14270,23.50900,21.78374,20.47938,19.80522,7777,301,2,39,1.274191e+19,QSO,7.011245,11317,58398,353,Redder Object
6178,1.237659e+18,229.108555,51.516024,24.04846,22.78807,21.51426,20.52233,19.77332,3225,301,4,122,9.452082e+18,QSO,7.011245,8395,57834,555,Redder Object
71744,1.237673e+18,347.394204,23.192555,26.78221,21.71899,20.29786,19.29930,19.03935,6354,301,4,176,7.419807e+18,QSO,7.011245,6590,56273,461,Redder Object
53375,1.237668e+18,164.524385,21.966377,24.77107,21.62430,19.98343,19.17728,18.73189,5183,301,5,223,7.237420e+18,QSO,7.011245,6428,56279,493,Redder Object
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39518,1.237680e+18,15.833059,30.322466,23.51236,23.47375,23.24541,21.54165,19.52259,8105,301,5,47,8.693348e+18,GALAXY,-0.005675,7721,57360,999,Redder Object
31976,1.237668e+18,241.444339,11.504581,22.63915,22.00861,21.91697,21.83613,21.57314,5317,301,4,120,5.859379e+18,GALAXY,-0.006055,5204,56036,714,Redder Object
8650,1.237665e+18,152.043506,33.555225,22.73689,21.89153,21.90507,21.91927,21.43474,4518,301,5,162,7.273397e+18,GALAXY,-0.006863,6460,56334,302,Bluer Object
66040,1.237652e+18,152.041107,64.524210,26.94855,23.41462,18.08402,22.93524,21.96446,1412,301,5,79,5.495439e+17,GALAXY,-0.007352,488,51914,381,Redder Object
46334,1.237668e+18,167.242339,17.894783,22.06989,21.51930,21.41494,21.30507,21.21390,5313,301,1,54,6.629341e+18,GALAXY,-0.009971,5888,56041,154,Redder Object

Suppose you want:
1. Group by class alphabetically.
2. Within each class, sort by redshift.

In [178]:
sdss17.sort_values(by=["class", "redshift"])

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,class,redshift,plate,MJD,fiber_ID,g_r_color
46334,1.237668e+18,167.242339,17.894783,22.06989,21.51930,21.41494,21.30507,21.21390,5313,301,1,54,6.629341e+18,GALAXY,-0.009971,5888,56041,154,Redder Object
66040,1.237652e+18,152.041107,64.524210,26.94855,23.41462,18.08402,22.93524,21.96446,1412,301,5,79,5.495439e+17,GALAXY,-0.007352,488,51914,381,Redder Object
8650,1.237665e+18,152.043506,33.555225,22.73689,21.89153,21.90507,21.91927,21.43474,4518,301,5,162,7.273397e+18,GALAXY,-0.006863,6460,56334,302,Bluer Object
31976,1.237668e+18,241.444339,11.504581,22.63915,22.00861,21.91697,21.83613,21.57314,5317,301,4,120,5.859379e+18,GALAXY,-0.006055,5204,56036,714,Redder Object
39518,1.237680e+18,15.833059,30.322466,23.51236,23.47375,23.24541,21.54165,19.52259,8105,301,5,47,8.693348e+18,GALAXY,-0.005675,7721,57360,999,Redder Object
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81625,1.237674e+18,131.056936,-1.468829,20.32929,20.11706,20.13314,20.17008,20.18296,6574,301,6,94,1.410191e+19,STAR,0.004153,12525,58932,51,Bluer Object
12096,1.237666e+18,54.355139,1.184638,22.62377,21.27744,20.61595,20.19472,20.22593,4849,301,6,818,1.708157e+18,STAR,0.004153,1517,52934,608,Redder Object
36137,1.237654e+18,172.374850,3.228694,18.72976,17.64982,17.28932,17.09305,16.98797,1992,301,5,150,5.766043e+17,STAR,0.004153,512,51992,522,Redder Object
71004,1.237664e+18,134.476162,28.659430,20.24982,20.12174,20.30250,20.46431,20.52874,4335,301,5,165,2.177607e+18,STAR,0.004153,1934,53357,425,Bluer Object
84706,1.237664e+18,36.001590,-0.819313,22.85609,21.96913,21.62495,21.63728,20.98113,4263,301,2,356,2.969023e+18,STAR,0.004153,2637,54115,92,Redder Object

In [179]:
(
    sdss17
    .groupby("class")["redshift"] # creates a GroupBy object and groups by class, and chooses redshift to work with
    .mean  # aggregation
    .sort_values(ascending=False) # sorts by average redshift
)

class
QSO       1.719676
GALAXY    0.421596
STAR     -0.000115
Name: redshift, dtype: float64

By default, sort_values() creates a new DataFrame. The original stays unchanged.

### sort_index()
To sort by index values, use the companion method sort_index(). This method has the same arguments and default order.

In [181]:
summary = sdss17.groupby("class")["redshift"].mean()
summary

class
GALAXY    0.421596
QSO       1.719676
STAR     -0.000115
Name: redshift, dtype: float64

summary.sort_index()

### concat()
For stacking tables, concat() is used to combine multiple pandas objects (DataFrames or Series) along a particular axis (vertically or horizontally). It basically stacks data on top of each other or side by side. It has five key parameters.

## Investigation
This is a good place to pause and use the pandas skills we learned to answer basic questions.

It has four parameters.
- objs → a list or mapping of DataFrames or Series to combine 
- axis → direction to concatenate (0 for vertical/rows, default, and 1 for horizontal/columns)
- join: how to handle mismatching indexes on the opposite axis ('outer' keeps all indexes, 'inner' keeps only overlapping indexes)
- ignore_index: if set to True, discards the original index markers and creates a continous label index from 0 to n-1
- keys: adds a multi-index layer to label each source DataFrame

By default, concat() stacks vertically

### Question 1
Which object type is most common?

In [7]:
sdss17['class'].value_counts()

class
GALAXY    59445
STAR      21594
QSO       18961
Name: count, dtype: int64

Results: Galaxies make up the majority of observations in this data set.

There are actually more stars than galaxies, but individual stars outside our local neighborhood are too faint to resolve individually, and are lumped together as galaxies.

### Question 2
Which object type has the highest average redshift?

In [15]:
sdss17.groupby("class")["redshift"].mean().sort_values(ascending=False)

class
QSO       1.719676
GALAXY    0.421596
STAR     -0.000115
Name: redshift, dtype: float64

Results: Quasars has the highest average redshift in this data set.

Quasars existed primarily in the early universe and are exceptionally luminous as they are powered by supermassive black holes, and therefore, can be spotted billions of light years away. Under Hubble's law, light from more distant objects stretches as the universe expands, resulting in a higher redshift. Unlike quasars, faint, low-power early objects cannot be seen at those distances.

### Question 3
How many objects were classified as blue vs. red?

In [20]:
sdss17["g_r_color"].value_counts()

g_r_color
Redder Object    95701
Bluer Object      4299
Name: count, dtype: int64

Results: We classified more objects as red than blue in our data set.

It's important to note that we set a hard threshold at 0 which is physicall arbitrary. The standard SDSS green and red filter do not split evenly at 0. In other words, the distinct physical types of stars, quasars, and galaxies do not neatly segregate at a single integer cut. Fixed color boundaries fail to account for nuances such as internal color gradiations or redsifts.

### Question 4
Which object type spans the greatest range of distances?

In [22]:
range_stats = sdss17.groupby("class")["redshift"].agg(["min", "max", "mean"])
range_stats['Range'] = range_stats['max'] - range_stats['min']
range_stats

             min       max      mean     Range
class
GALAXY -0.009971  1.995524  0.421596  2.005495
QSO     0.000461  7.011245  1.719676  7.010784
STAR   -0.004136  0.004153 -0.000115  0.008289

Results: In our data set, quasars show the largest range of distance.

Because quasars are extremely luminous and outshine entire galaxies, they are visible over enormous spans of space and cosmic voids where regular galaxies disappear.

### Question 5
Do different object classes have different average magnitudes across the filters?

In [23]:
sdss17.groupby("class")[["u", "g", "r", "i", "z"]].mean()

                u          g          r          i          z
class
GALAXY  22.587379  20.906101  19.587552  18.851990  18.449156
QSO     21.547619  20.926193  20.624089  20.431173  20.266732
STAR    20.689805  19.153188  18.946969  18.543736  17.870400

NOTE: These are magnitudes. The smaller it is, the brighter.
    
Results: Stars have the lowest average magnitude in every filter, which means they are the brightest objects in this sample on average. Quasars have the highest average magnitudes in most filters, meaning they are the faintest objects on average.

Despite what we said of quasars being intrinsically very luminous, they often appear very faint from Earth, so this actually makes sense with Question 2 where we found that quasars have highest average redshifts in our data set.

# Conclusion

In this project, I explored the Sloan Digital Sky Survey (SDSS) dataset using pandas to better understand its structure and the types of information it contains. I learned how to inspect a dataset, filter observations, create new features with map() and apply(), group data to calculate summary statistics, and sort results to identify patterns.

From the analysis, I found that galaxies make up the largest portion of the dataset, while quasars have the highest average redshift, suggesting they are generally the most distant objects in the survey. I also observed differences in the average magnitudes of stars, galaxies, and quasars across the SDSS filters, indicating that each object class has distinct observational characteristics.

Although this exploration relied primarily on tables and summary statistics, it raised several questions that would be easier to investigate with visualizations. In the next part, I will use plots and charts to explore these patterns in greater detail.